config/routes.rb
XdMailCompiler::Application.routes.draw do

  root 'campaigns#index'

  resources :campaigns do
    collection do
       get :collect_resources # for campaign
      post :select_resource   # ajax load in
    end
    member do
      get :preview
    end
  end

  resources :resources

  resources :exports do
    collection do
      get :preflight_for_email_on_acid
    end
  end

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  belongs_to :client
  has_many :resources

  def ordered_stylesheets markup_name, scope = "all"
    # what is the markup document? e.g. california.html
    filename_string = markup_name.split('.').first

    # what should we retrieve? styles for the head? for the body to be inlined?
    scope = scope.to_s

    # return an array of requested resources in the proper parsing order
    o = []
    patterns_array = stylesheet_sorting_patterns(filename_string, scope)
    patterns_array.each do |query|
      if matches = resources.stylesheets.where("file_file_name LIKE ?", query)
        matches.each do |match|
          o.push match
        end
      end
    end
    o
  end

  def style_files_for_markup(markup_record, type)
    stylesheets = ordered_stylesheets(File.basename(markup_record.file_file_name), type).map do |pca|
      File.new("public#{pca.file.url[/[^?]+/]}") # pca = paperclip attachment
    end
    stylesheets
  end

  def stylesheet_sorting_patterns markup_name, scope = "all"
    # ORDER OF COMPILATION/SPECIFICITY
    #   BODY:
    #     reset.css, reset_1.css, global.css, global_1.css
    #     california.css, california_1.css
    #   HEAD:
    #     global_head.css, global_head_1.css
    #     california_head.css, california_head_1.css
    scopes = {
      head: [
        "global_head\.%",
        "global_head_[0-9]*\.%",
        "#{markup_name}_head\.%",
        "#{markup_name}_head_[0-9]*\.%"
      ],
      inline: [
        "reset\.%",
        "reset_[0-9]*\.%",
        "global\.%",
        "global_[0-9]*\.%",
        "#{markup_name}\.%",
        "#{markup_name}_[0-9]*\.%"
      ]
    }
    patterns = case scope
    when "head", "inline"
      scopes[scope.to_sym]
    else
      (scopes[:head] | scopes[:inline])
    end
    patterns
  end

  def reset_cache
    resources.markups.each do |markup|
      markup.cached_compilation = nil
      markup.cache_valid = false
      markup.save
    end
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  before_filter :get_campaign, only: [:show, :destroy, :collect_resources, :select_resource, :get_markups, :get_compiled_html]

  def index
    @campaigns   ||= Campaign.order(:created_at).reverse_order
  end

  def show
    session[:campaign_id] = params[:id]
  end

  def preview
    collect_resources
    respond_to do |format|
      format.js
    end
  end

  def create
    Campaign.create campaign_params
    redirect_to :back
  end

  def destroy
    @campaign.destroy
    redirect_to :back
  end

  def select_resource
    session[:sel_mu_id] = params[:selected_markup] if params[:selected_markup]
    collect_resources
    respond_to do |format|
      format.js
    end
  end

private

  def get_campaign
    campaign_id ||= params[:id] || session[:campaign_id]
    @campaign ||= Campaign.find(campaign_id)
  end

  def get_markups
    @markup_docs = @campaign.resources.markups
  end

  def collect_resources
    get_markups
    @selected_markup = @markup_docs.find(session[:sel_mu_id])

    get_compiled_html @selected_markup
  end

  def get_compiled_html markup_record
    markup_file = File.new(markup_record.file.path)
    if markup_record.cache_valid?
      compiled_tree = Nokogiri::HTML(markup_record.cached_compilation)
    else
      inline_stylesheets = @campaign.style_files_for_markup(markup_record, :inline)
      head_stylesheets = @campaign.style_files_for_markup(markup_record, :head)
      compiled_tree = Compiler::Markup.render(markup_file, inline_stylesheets, head_stylesheets)

      # title = Nokogiri::XML::Element.new('title', compiled_tree)
      # title.content = ""
      # compiled_tree.children.first.add_previous_sibling(title)

      markup_record.cached_compilation = compiled_tree.to_html
      markup_record.cache_valid = true
      markup_record.save
    end
    @rendered_html_app_imgs   = Resource.app_relative_paths(compiled_tree.dup, @campaign)
    @shl_rendered_html        = Compiler.syntax_highlight markup_record.cached_compilation, :html
  end

  def campaign_params
    params.require(:campaign).permit(:name)
  end
  
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_resource_row.html.haml
%tr
  %td
    - if resource_type == :markup
      = radio_button_tag "selected_#{resource_type}", resource.id
    - if resource_type == :image
      =link_to resource.image.url, {class: :fancybox, data: {thumb: resource.image.url(:thumb)}} do
        =strip_query(File.basename resource.image.url)
    - else
      = link_to resource_path(resource.id), {class: 'fancybox-ajax'} do
        = strip_query(File.basename resource.file.url)

  %td
    =link_to resource_path(resource.id), {class: 'btn btn-xs btn-default danger-hover', method: :delete, data:{confirm: "Are you certain you want to remove this resource from this campaign? You cannot undo this."}} do
      %i.fa.fa-trash-o

app/views/campaigns/index.html.haml
- content_for :javascripts do
  = javascript_include_tag :campaign_dashboard

.row
  .col-sm-6
    %h2 Choose your Campaign
    #campaign-preview
  .col-sm-6
    %table.table.table-striped.table-condensed
      %thead
        %tr
          %th Campaign Name
          %th Actions
      %tbody
        %tr
          %td{colspan: 2}
            = form_for :campaign, url: {action: :create}, html: {class: 'form-inline'} do |f|
              .form-group= f.text_field :name, value: nil, class: 'form-control'
              .form-group= f.submit "Create New Campaign", class: 'btn btn-default btn-xs form-control'
        - @campaigns.each do |campaign|
          %tr
            %td= link_to campaign.name, campaign_path(campaign.id)
            %td
              = link_to 'Preview', preview_campaign_path(campaign.id), {class: 'preview campaign btn btn-xs btn-default', remote: true}
              = link_to 'Delete', campaign_path(campaign.id), {class: 'delete campaign btn btn-xs btn-default danger-hover', method: :delete, data: {confirm: "Are you certain you want to delete this campaign? You can't get it back!"}}

app/views/campaigns/preview.js.erb
$(function(){
  $('#campaign-preview').html("<%= raw escape_javascript(@rendered_html_app_imgs.to_html) %>");
})

app/views/campaigns/show.html.haml
-content_for :javascripts do
  =javascript_include_tag 'campaign_show'

#dropzone
  .row
    %h4.col-sm-9 Upload files by dragging them onto this dotted area
    #progress-target.col-sm-3
      .progress.progress-striped.active
        .progress-bar{role: :progressbar, style: "width: 0%;", aria:{valuenow: 0, valuemin: 0, valuemax: 100}}

=form_tag select_resource_campaigns_path, remote: true do
  .row
    -{image: 'picture-o', markup: 'code', stylesheet: 'leaf'}.each do |resource_type, icon|
      .col-sm-4.resources{id: "#{resource_type}-resources"}
        %h4
          %i{class: "fa fa-#{icon}"}
          #{resource_type.to_s.capitalize} Resources
        .table-wrapper
          %table.table.table-striped.table-condensed
            %tbody
              -@campaign.resources.send((resource_type.to_s.pluralize)).each do |resource|
                =render partial: "resource_row", locals: {resource: resource, resource_type: resource_type}
.row
  %h3.col-sm-9 Output
  = link_to preflight_for_email_on_acid_exports_path, {class: 'col-sm-3 btn btn-xs btn-default'} do
    Export resources for
    %br
    =image_tag 'eoa-favicon.png'
    Email on Acid

.row
  .col-sm-6#compiled-source-preview
  .col-sm-6#compiled-browser-preview